#pragma once

// Public C++ development surface. This intentionally includes the canonical
// engine headers only; the legacy runtime/sdl declaration mirrors are not API.
#include "Config.hpp"
#include "asset/Animation.hpp"
#include "asset/Font.hpp"
#include "asset/Resource.hpp"
#include "asset/Scene.hpp"
#include "asset/Sound.hpp"
#include "asset/Texture.hpp"
#include "component/Collider.hpp"
#include "component/Rigidbody.hpp"
#include "component/Sprite.hpp"
#include "component/Tag.hpp"
#include "component/Transform.hpp"
#include "core/Entity.hpp"
#include "core/Manager.hpp"
#include "device/GPUDevice.hpp"
#include "device/GPUPipeline.hpp"
#include "device/Input.hpp"
#include "device/Key.hpp"
#include "device/Shader.hpp"
#include "device/Window.hpp"
#include "math/Math.hpp"
#include "system/Collision.hpp"
#include "system/Event.hpp"
#include "system/Hierarchy.hpp"
#include "system/Movement.hpp"
#include "util/Debugger.hpp"
#include "util/Profiler.hpp"
#include "util/Timer.hpp"
#include "view/Border.hpp"
#include "view/Button.hpp"
#include "view/Camera.hpp"
#include "view/Label.hpp"
